version: '3.1'

services:

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - ./files:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./script/localstack/s3/init-s3-bucket.sh:/docker-entrypoint-initaws.d/init-s3-bucket.sh
      - ./aws:/docker-entrypoint-initaws.d//buckets.sh