spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    stream:
      bindings:
        input:
          group: songs
          content-type: text/plain

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MB

resilience4j:
  retry:
    instances:
      resource-service:
        maxAttempts: 3
        waitDuration: 10s
      song-service:
        maxAttempts: 3
        waitDuration: 10s
